apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api-deploy
  name: api-deploy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: api-deploy
  type: NodePort
status:
  loadBalancer: {}
